image:
  repository: jonilsonds9/playground-gitops-argo-cd
  tag: 08c3e2698d46e7f905eb6ed9e1176abda5f54656
  pullPolicy: IfNotPresent

nameOverride: "beta"
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

env:
  SPRING_PROFILES_ACTIVE: "beta"
