image:
  repository: jonilsonds9/playground-gitops-argo-cd
  tag: baa1bf922d9486b776da341d2a62ffd56f1e3a10
  pullPolicy: IfNotPresent

nameOverride: "beta"
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

env:
  SPRING_PROFILES_ACTIVE: "beta"
