image:
  repository: jonilsonds9/playground-gitops-argo-cd
  tag: c1fe5a26abbb58249f411d42ad9ebc4bf54ac25e
  pullPolicy: IfNotPresent

nameOverride: "beta"
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

env:
  SPRING_PROFILES_ACTIVE: "beta"
