image:
  repository: jonilsonds9/playground-gitops-argo-cd
  tag: 1a182ddc8bc0b7487ab252f53b3894b646cc1530
  pullPolicy: IfNotPresent

nameOverride: "beta"
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

env:
  SPRING_PROFILES_ACTIVE: "beta"
