image:
  repository: jonilsonds9/playground-gitops-argo-cd
  tag: e23664f80284a8c5fe754bbb6ad33e369f4fa497
  pullPolicy: IfNotPresent

nameOverride: "beta-prod"
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

env:
  SPRING_PROFILES_ACTIVE: "beta-prod"
